apiVersion: v1
kind: Service
metadata:
  name: educationelly-server
  namespace: educationelly
  labels:
    app: educationelly-graphql
    component: server
spec:
  type: ClusterIP
  selector:
    app: educationelly-graphql
    component: server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
